 
GET http://localhost:3000/noticias/listarNoticias

###
POST http://localhost:3000/noticias/criarNoticia
Content-Type: application/json

{
    "titulo": "Título da Matéria",
    "descricao": "Descrição da Matéria",
    "data_publicacao": "2024-01-30 12:00:00",
    "assunto": "Assunto da Matéria",
    "texto_materia": "Conteúdo da Matéria...",
    "autor": "Nome do Autor"
}

###
PUT http://localhost:3000/noticias/editarNoticia/1
Content-Type: application/json

{
    "titulo": "Título da Matéria 2",
    "descricao": "Descrição da Matéria 2.1",
    "data_publicacao": "2024-01-31 14:00:00",
    "assunto": "Assunto da Matéria 2.3",
    "texto_materia": "Conteúdo da Matéria 1. 2. 3.",
    "autor": "Nome do Autor 4.1"
}

###
DELETE http://localhost:3000/noticias/deletarNoticia/2